spring.application.name=*
spring.datasource.url=$
spring.datasource.username=$
spring.datasource.password=$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


aws.accessKeyId=$
aws.secretKey=$
aws.s3.bucketName=unidosti-apartment-images
aws.s3.region=us-east-2

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=$
server.ssl.key-store-password=$
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat



#Removing because of credentials